<?php include VIEW_SCRIPTS.'index/templates/default_header.phtml' ?>
<script type="text/javascript">

var json_namelist_str = '';
function matchPattern()
{
    console.log('Inside matchPattern()');
    recipient_list = $('#msg_to').val();
    arr_recipient_list = recipient_list.split(',');
    
    pattern = new RegExp(arr_recipient_list[arr_recipient_list.length-1].trim(), 'i');/*'i' for case insensetive'*/
    console.log(arr_recipient_list[arr_recipient_list.length-1]);
    matches = '';
    
    arr_names = JSON.parse(json_namelist_str);
    
    for(i=0; i<arr_names.length; i++)
    {
        //console.log("Display Name:"+arr_names[i].displayname);
        //console.log("Full Name:"+arr_names[i].fullname);

        //check if fullname or display name matches input string
        if(pattern.test(arr_names[i].displayname) || pattern.test(arr_names[i].fullname))
        {
            matches += '<li><span>'+ arr_names[i].fullname +'</span> '+ arr_names[i].displayname +'</li>';
        }
    }			
    //display auto-suggestion list
    $('ul.autoSuggest').html(matches);
}
function getSuggestions(fulltext, event)
{
	console.log('Inside getSuggestions()');
        var ipLength = fulltext.length;
	var comma_position = fulltext.lastIndexOf(",");
	var retaintext = fulltext.substr(0, comma_position);
	var searchtext = fulltext.substr(comma_position+1, ipLength);
	searchtext = searchtext.replace(/^\s*|\s*$/g,'');
	
	var xmlhttp;
	
        if (window.XMLHttpRequest)
	{// code for IE7+, Firefox, Chrome, Opera, Safari
		xmlhttp=new XMLHttpRequest();
	}
	else
	{// code for IE6, IE5
		xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
	}
	
        xmlhttp.onreadystatechange=function()
	{
            if (xmlhttp.readyState==4 && xmlhttp.status==200)
            {
                op_elementId = 'suggestion';
                json_namelist_str = xmlhttp.responseText;
                //console.log(json_namelist_str);

                //console.log(arr_names.length);
                matchPattern();               			
            }
	}
        if(ipLength > 0 && !document.getElementById('msg_to').focus() && 
            event.keyCode != 8 && event.keyCode != 188 && event.keyCode != 39 &&
            event.keyCode != 32 && event.keyCode !=40 && event.keyCode !=38 &&
            event.keyCode != 13)
        {
            //javascript keycodes// backspace 8, comma 188, right arrow 39, white space 32
            if(json_namelist_str == '')
            {
                xmlhttp.open("GET","index.php?rt=profile/suggestName",true);
                xmlhttp.send();
            } 
            else
                matchPattern();
        }
        
        if(event.keyCode == 40) /* DOWN key */
        {
            is_highlighted = $('ul.autoSuggest li.highlight').size();
            console.log(is_highlighted);
            if( is_highlighted == 1 )
            {
                cur_el = $('ul.autoSuggest li.highlight');
                $(cur_el).removeClass('highlight');
                $(cur_el).next().addClass('highlight');
                console.log('Inside if - down');
            }
            else
            {
                $('ul.autoSuggest li:first-child').addClass('highlight');
                console.log('Inside else - down');
            }
        } 
        else if(event.keyCode == 38) /* UP key */
        {
            if( $('ul.autoSuggest li.highlight').size() == 1 )
            {
                cur_el = $('ul.autoSuggest li.highlight');
                $(cur_el).removeClass('highlight');
                $(cur_el).prev().addClass('highlight');
                console.log('Inside if - up');
            }
            else
            {
                $('ul.autoSuggest li:last-child').addClass('highlight');
                console.log('Inside else - up');
            }
        }
        
        else if(event.keyCode == 27) /* ESC key */
        {
            removeSuggestionBox();
            //$('#item_code').select();
        }
        else if(event.keyCode == 13) /* ENTER key */
        {
            console.log('Inside Enter block');
            is_highlighted = $('ul.autoSuggest li.highlight').size();
            if( is_highlighted == 1 )
            {
                console.log(is_highlighted);
                full_n_display = $('ul.autoSuggest li.highlight').html(); 
                console.log(full_n_display);
                split_full_disp = full_n_display.split('</span>'); 
                console.log(split_full_disp[1].trim());
                disp_name = split_full_disp[1].trim();
                console.log(disp_name);
                
                addToRecipients(disp_name);
                
                //RESET ITEM NAME AND SUGGESTIONS
               // $('#msg_to').val('');
                $('ul.autoSuggest').html('');
            }
        }
return false;
}
function addToRecipients(disp_name)
{
	console.log('Inside addToRecipients()');
        retainValue = document.getElementById('msg_to').value;
	var recipientList = '';
	arrNames = retainValue.split(',');
	
	if(arrNames.length == 1)
        {    
            console.log('Inside if');
            document.getElementById('msg_to').value = disp_name+', ';
            console.log(document.getElementById('msg_to').value);
        }
	else
	{   
            console.log('Inside else');
            match_found = false;
            for(i=0; i<arrNames.length-1;i++)
            {
                    if(recipientList == '')
                            recipientList = arrNames[i].replace(/^\s\s*/, '').replace(/\s\s*$/, '');
                    else
                            recipientList = recipientList+', '+arrNames[i].replace(/^\s\s*/, '').replace(/\s\s*$/, '');
                    
                    if(disp_name == arrNames[i].trim())
                        match_found = true;
            }
            if(!match_found)
                document.getElementById('msg_to').value = recipientList+', '+disp_name+', ';
            else
                document.getElementById('msg_to').value = recipientList+', ';
        }
	document.getElementById('msg_to').focus();	
}

function removeRecipients()
{
	document.getElementById('msg_to').value='';
	document.getElementById('msg_to').focus();
}

</script>
<script src="<?php echo JS; ?>electrix_javascripts.js" type="text/javascript"></script>
<p class="title">Compose new message</p>
<br />
<?php include("messages_menu.phtml"); ?>
<br />
<form id="compose_msg" method="post" action="index.php?rt=messages/compose">
<table border="0" cellpadding="5" cellspacing="0">
    
<tr>
    <td valign="top"><label for="msg_to">To</label></td>
    <td>
        <input type="text" id="msg_to" name="msg_to" 
               tabindex="1" autocomplete="off"
               onfocus="showSuggestionBox()"
               onblur="removeSuggestionBox()"
               onkeyup="getSuggestions(this.value, event)" placeholder="Enter display name or full name"
               value =" <?php if(isset($recipients)) echo $recipients; ?>"/>
        &nbsp;
        <input type="button" class="smallButton" value="Remove all" onclick="removeRecipients()" />
        <br />
        <span id="suggestion" style="color:#CCC"></span>
    </td>
</tr>

<tr>
    	<td><label for="msg_subject">Subject</label></td>
        <td><input type="text" id="msg_subject" name="msg_subject" maxlength="32" tabindex="2" 
                   value="<?php if ( isset($subject)) echo($subject); ?>"/></td>
</tr>
<tr>
    <td valign="baseline">Message</td>
    <td>
        <textarea name="msg_body" id="msg_body" rows="5" tabindex="3" 
                  placeholder="Limit to 200 characters"><?php if(isset($msgBody)) echo($msgBody); ?></textarea>
    </td>
</tr>

<tr>
    <td><input type="hidden" name="reply_to_msg" value="<?php if ( isset($replyToMsgId)) echo($replyToMsgId); ?>" /></td>
    <td>
        <input id="msg_send" type="button" value="Send" class="button" onclick="sendPrivateMessage()"/><br/><br/>
        <?php if ( isset($message))  echo($message); ?>
    </td>
</tr>

</table>
<p style="font-size:11px; width:538px">
<strong>Tip:</strong>
Use only DISPLAY NAME while composing messages. When you type in a name in the 'to' field, suggestions appear instantly as shown in the <a href="http://www.youtube.com/watch?v=cKsumoGK6W0" target="_blank">video</a>. Just type the dark colored name that appears in the suggestion, or use the 'Add' link.
</p>
</form>
<?php include VIEW_SCRIPTS.'index/templates/default_footer.phtml' ?>