<?php include VIEW_SCRIPTS.'index/templates/default_header.phtml' ?>
<link href="<?php echo JS; ?>plugins/jquery.imgareaselect-0.9.8/css/imgareaselect-default.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php echo JS; ?>plugins/jquery.imgareaselect-0.9.8/scripts/jquery.imgareaselect.pack.js"></script>
<script type="text/javascript">

function preview(img, selection) {
    var scaleX = 100 / (selection.width || 1);
    var scaleY = 100 / (selection.height || 1);
    $('#photo + div > img').css({
        width: Math.round(scaleX * $(img).width()) + 'px',
        height: Math.round(scaleY * $(img).height()) + 'px',
        marginLeft: '-' + Math.round(scaleX * selection.x1) + 'px',
        marginTop: '-' + Math.round(scaleY * selection.y1) + 'px'
    });
} 

$(document).ready(function () {
    $('<div><img src="<?php echo IMAGES; ?>profilepics/<?php echo $_SESSION['myid']; ?>_uncropped.jpg" style="position: relative;" /><div>') .css({
        'float': 'left',
        'position': 'relative',
        'overflow': 'hidden',
        'width': '100px',
        'height': '100px'
    }) .insertAfter($('#photo')); 

    $('#photo').imgAreaSelect({
        aspectRatio: '1:1',
        handles: true,
        onSelectChange: preview,
        onSelectEnd: function (img, selection ) {
            $('input[name=x1]').val(selection.x1);
            $('input[name=y1]').val(selection.y1);
            $('input[name=x2]').val(selection.x2);
            $('input[name=y2]').val(selection.y2);
            $('input[name=w]').val(selection.width);
            $('input[name=h]').val(selection.height);
        }
    });
}); 

</script>
<p class="title">Profile pic</p>
<br/>
<p>
    <img id="photo" src="<?php echo IMAGES; ?>profilepics/<?php echo $_SESSION['myid']; ?>_uncropped.jpg" alt="" title="" style="margin: 0 0 0 10px;" />
</p>

<form action="index.php?rt=profile/crop" method="post">
    <input type="hidden" name="x1" value="" />
    <input type="hidden" name="y1" value="" />
    <input type="hidden" name="x2" value="" />
    <input type="hidden" name="y2" value="" />
    <input type="hidden" name="w" value="" />
    <input type="hidden" name="h" value="" />
    <input type="submit" value="Crop" />
</form>
<?php include VIEW_SCRIPTS.'index/templates/default_footer.phtml' ?>